# backend/historical_games.py

HISTORICAL_GAMES_METADATA = [
    {
        "id": "2016_finals_g7",
        "title": "2016 NBA Finals Game 7: CLE vs GSW",
        "date": "June 19, 2016",
        "desc": "The Block, The Shot, The Stop. Cavaliers complete the historic 3-1 comeback against the 73-9 Warriors."
    },
    {
        "id": "2023_playoffs_lal_gsw",
        "title": "2023 Playoffs Game 6: LAL vs GSW",
        "date": "May 12, 2023",
        "desc": "LeBron and the Lakers close out the Warriors in a heated Western Conference playoff battle."
    }
]

HISTORICAL_GAMES_TIMELINES = {
    # ─────────────────────────────────────────────
    # 2016 NBA FINALS GAME 7 — FULL GAME
    # ─────────────────────────────────────────────
    "2016_finals_g7": [
        # ── Q1 ──
        {"clock": "12:00", "quarter": "Q1", "score": "CLE 0 - 0 GSW",  "desc": "Tip-off! LeBron James wins the opening tip for Cleveland.", "isHighlight": False},
        {"clock": "11:31", "quarter": "Q1", "score": "CLE 2 - 0 GSW",  "desc": "LeBron James drives hard to the rim and puts it up off the glass.", "isHighlight": False},
        {"clock": "11:05", "quarter": "Q1", "score": "CLE 2 - 3 GSW",  "desc": "Klay Thompson answers with an effortless midrange jumper.", "isHighlight": False},
        {"clock": "10:41", "quarter": "Q1", "score": "CLE 5 - 3 GSW",  "desc": "Kyrie Irving splits the defense and lays it in!", "isHighlight": False},
        {"clock": "10:02", "quarter": "Q1", "score": "CLE 5 - 6 GSW",  "desc": "Stephen Curry nails a pull-up three to take the lead!", "isHighlight": True},
        {"clock": "9:28",  "quarter": "Q1", "score": "CLE 7 - 6 GSW",  "desc": "Kevin Love posts up and hits a tough turnaround over Durant.", "isHighlight": False},
        {"clock": "9:01",  "quarter": "Q1", "score": "CLE 7 - 9 GSW",  "desc": "Draymond Green finds Durant cutting to the hoop for an easy two.", "isHighlight": False},
        {"clock": "8:30",  "quarter": "Q1", "score": "CLE 9 - 9 GSW",  "desc": "LeBron James ties it up with a mid-post fadeaway.", "isHighlight": False},
        {"clock": "8:02",  "quarter": "Q1", "score": "CLE 9 - 12 GSW", "desc": "Curry again! Back-to-back three pointers from the logo!", "isHighlight": True},
        {"clock": "7:28",  "quarter": "Q1", "score": "CLE 11 - 12 GSW","desc": "J.R. Smith hits a corner three to keep Cleveland in it.", "isHighlight": False},
        {"clock": "7:05",  "quarter": "Q1", "score": "CLE 11 - 14 GSW","desc": "Livingston posts up and hooks it over Kyrie for two.", "isHighlight": False},
        {"clock": "6:31",  "quarter": "Q1", "score": "CLE 14 - 14 GSW","desc": "Kyrie Irving with a step-back three! Game tied again.", "isHighlight": True},
        {"clock": "5:52",  "quarter": "Q1", "score": "CLE 14 - 17 GSW","desc": "Klay Thompson goes backdoor for an and-one layup and hits the free throw too!", "isHighlight": True},
        {"clock": "5:18",  "quarter": "Q1", "score": "CLE 16 - 17 GSW","desc": "LeBron forces the issue and gets to the line, hits both.", "isHighlight": False},
        {"clock": "4:50",  "quarter": "Q1", "score": "CLE 16 - 20 GSW","desc": "Green hits a mid-range off a Curry drive-and-kick.", "isHighlight": False},
        {"clock": "4:15",  "quarter": "Q1", "score": "CLE 19 - 20 GSW","desc": "Tristan Thompson pounds one home off an offensive rebound!", "isHighlight": False},
        {"clock": "3:40",  "quarter": "Q1", "score": "CLE 19 - 22 GSW","desc": "Iguodala pushes it in transition off a LeBron turnover.", "isHighlight": False},
        {"clock": "3:08",  "quarter": "Q1", "score": "CLE 22 - 22 GSW","desc": "LeBron James with a THUNDEROUS one-handed put-back slam!", "isHighlight": True},
        {"clock": "2:30",  "quarter": "Q1", "score": "CLE 22 - 25 GSW","desc": "Curry goes isolation on Kyrie and drains a fadeaway three.", "isHighlight": True},
        {"clock": "1:50",  "quarter": "Q1", "score": "CLE 25 - 25 GSW","desc": "Shumpert hits from the corner to even it up.", "isHighlight": False},
        {"clock": "1:10",  "quarter": "Q1", "score": "CLE 25 - 28 GSW","desc": "Durant finishes over LeBron at the buzzer-beater of Q1!", "isHighlight": True},
        # ── Q2 ──
        {"clock": "12:00", "quarter": "Q2", "score": "CLE 25 - 28 GSW","desc": "Second quarter begins. Warriors take a 3-point lead into the break.", "isHighlight": False},
        {"clock": "11:22", "quarter": "Q2", "score": "CLE 28 - 28 GSW","desc": "J.R. Smith drifts to the corner and fires — bang! Tied up.", "isHighlight": False},
        {"clock": "10:50", "quarter": "Q2", "score": "CLE 28 - 31 GSW","desc": "Barnes hits a three off the right wing. Warriors respond.", "isHighlight": False},
        {"clock": "10:15", "quarter": "Q2", "score": "CLE 31 - 31 GSW","desc": "LeBron James back-to-back possessions — iso drive, foul, 2 free throws.", "isHighlight": False},
        {"clock": "9:45",  "quarter": "Q2", "score": "CLE 31 - 34 GSW","desc": "Curry and Klay play hot potato on the perimeter; Klay fires and nails it!", "isHighlight": True},
        {"clock": "9:10",  "quarter": "Q2", "score": "CLE 33 - 34 GSW","desc": "Kyrie Irving draws a charge on Draymond Green and scores!", "isHighlight": False},
        {"clock": "8:30",  "quarter": "Q2", "score": "CLE 36 - 34 GSW","desc": "Tristan Thompson with BACK-TO-BACK offensive boards and tips it in!", "isHighlight": True},
        {"clock": "7:55",  "quarter": "Q2", "score": "CLE 36 - 37 GSW","desc": "Iguodala hits a cutting layup off a textbook Draymond pass.", "isHighlight": False},
        {"clock": "7:20",  "quarter": "Q2", "score": "CLE 38 - 37 GSW","desc": "LeBron James posts up Barnes and finishes the up-and-under.", "isHighlight": False},
        {"clock": "6:42",  "quarter": "Q2", "score": "CLE 38 - 40 GSW","desc": "Curry pulls up from 30 feet. IT GOES IN! How is that even legal?", "isHighlight": True},
        {"clock": "6:08",  "quarter": "Q2", "score": "CLE 41 - 40 GSW","desc": "LeBron hits a three pointer! Cleveland takes the lead!", "isHighlight": True},
        {"clock": "5:28",  "quarter": "Q2", "score": "CLE 41 - 43 GSW","desc": "Green dishes to Durant on the roll, easy basket.", "isHighlight": False},
        {"clock": "4:50",  "quarter": "Q2", "score": "CLE 43 - 43 GSW","desc": "Kyrie crosses over three Warriors and scores again!", "isHighlight": True},
        {"clock": "4:11",  "quarter": "Q2", "score": "CLE 43 - 46 GSW","desc": "Klay Thompson again! A catch from the corner, zero hesitation.", "isHighlight": False},
        {"clock": "3:30",  "quarter": "Q2", "score": "CLE 46 - 46 GSW","desc": "LeBron throws an alley-oop to Tristan Thompson!", "isHighlight": True},
        {"clock": "2:55",  "quarter": "Q2", "score": "CLE 46 - 49 GSW","desc": "Durant hits a marathon jumper late in the shot clock.", "isHighlight": False},
        {"clock": "2:10",  "quarter": "Q2", "score": "CLE 49 - 49 GSW","desc": "Love hits back! Big 3-pointer from the top of the key.", "isHighlight": False},
        {"clock": "1:22",  "quarter": "Q2", "score": "CLE 49 - 51 GSW","desc": "Curry draws a foul on LeBron and hits both free throws.", "isHighlight": False},
        {"clock": "0:45",  "quarter": "Q2", "score": "CLE 51 - 51 GSW","desc": "LeBron hits a floater from 10 feet in the lane! Tied at 51.", "isHighlight": False},
        {"clock": "0:11",  "quarter": "Q2", "score": "CLE 51 - 51 GSW","desc": "Curry's half court shot at the buzzer is no good. We go to halftime tied!", "isHighlight": False},
        # ── Q3 ──
        {"clock": "12:00", "quarter": "Q3", "score": "CLE 51 - 51 GSW","desc": "Halftime is over. One half of basketball decides the NBA champion.", "isHighlight": False},
        {"clock": "11:30", "quarter": "Q3", "score": "CLE 53 - 51 GSW","desc": "LeBron James immediately goes back to work — hook shot over the top.", "isHighlight": False},
        {"clock": "10:55", "quarter": "Q3", "score": "CLE 53 - 54 GSW","desc": "Klay Thompson hits a baseline jumper off a pin-down screen.", "isHighlight": False},
        {"clock": "10:15", "quarter": "Q3", "score": "CLE 56 - 54 GSW","desc": "Kyrie Irving with a nifty snake dribble and reverse layup!", "isHighlight": True},
        {"clock": "9:40",  "quarter": "Q3", "score": "CLE 56 - 57 GSW","desc": "Durant hits the mid-range in isolation. The man is so difficult to guard.", "isHighlight": False},
        {"clock": "9:05",  "quarter": "Q3", "score": "CLE 58 - 57 GSW","desc": "James gets fouled driving through two Warriors and sinks one of two.", "isHighlight": False},
        {"clock": "8:28",  "quarter": "Q3", "score": "CLE 58 - 60 GSW","desc": "Curry hits two free throws after LeBron bumps him on a drive.", "isHighlight": False},
        {"clock": "7:50",  "quarter": "Q3", "score": "CLE 61 - 60 GSW","desc": "JAMES! Three possession blocks from LeBron in a row!", "isHighlight": True},
        {"clock": "7:15",  "quarter": "Q3", "score": "CLE 61 - 63 GSW","desc": "Barnes hits a corner three off a Curry drive.", "isHighlight": False},
        {"clock": "6:40",  "quarter": "Q3", "score": "CLE 64 - 63 GSW","desc": "Love hits a corner three! Cleveland reclaims the lead!", "isHighlight": True},
        {"clock": "6:05",  "quarter": "Q3", "score": "CLE 64 - 66 GSW","desc": "Draymond Green makes two free throws after getting slapped on a drive.", "isHighlight": False},
        {"clock": "5:28",  "quarter": "Q3", "score": "CLE 67 - 66 GSW","desc": "LeBron pounds down the lane and gets an and-one!", "isHighlight": True},
        {"clock": "4:50",  "quarter": "Q3", "score": "CLE 67 - 69 GSW","desc": "Iguodala with a gorgeous euro-step layup.", "isHighlight": False},
        {"clock": "4:15",  "quarter": "Q3", "score": "CLE 70 - 69 GSW","desc": "Kyrie Irving hits a step-back jumper out of a pick-and-roll!", "isHighlight": False},
        {"clock": "3:35",  "quarter": "Q3", "score": "CLE 70 - 71 GSW","desc": "Thompson slips around the screen and sinks a mid-range.", "isHighlight": False},
        {"clock": "2:58",  "quarter": "Q3", "score": "CLE 72 - 71 GSW","desc": "J.R. Smith drives baseline and scores with the reverse!", "isHighlight": False},
        {"clock": "2:20",  "quarter": "Q3", "score": "CLE 72 - 74 GSW","desc": "Curry and Klay combo — Curry drives, kicks to Klay, THREEEE!", "isHighlight": True},
        {"clock": "1:42",  "quarter": "Q3", "score": "CLE 75 - 74 GSW","desc": "LeBron hits both free throws to put Cleveland back in front!", "isHighlight": False},
        {"clock": "1:05",  "quarter": "Q3", "score": "CLE 75 - 76 GSW","desc": "Livingston hits two free throws off a foul from LeBron.", "isHighlight": False},
        {"clock": "0:28",  "quarter": "Q3", "score": "CLE 75 - 76 GSW","desc": "LeBron's corner three hits the back iron. Q3 ends with Warriors up 1.", "isHighlight": False},
        # ── Q4 ──
        {"clock": "12:00", "quarter": "Q4", "score": "CLE 75 - 76 GSW", "desc": "FINAL QUARTER. The entire NBA season comes down to these 12 minutes.", "isHighlight": False},
        {"clock": "11:15", "quarter": "Q4", "score": "CLE 75 - 76 GSW", "desc": "LeBron passes out to Shumpert, misses a three-pointer.", "isHighlight": False},
        {"clock": "10:50", "quarter": "Q4", "score": "CLE 75 - 78 GSW", "desc": "Livingston drives the baseline and dunks it over Thompson!", "isHighlight": True},
        {"clock": "10:11", "quarter": "Q4", "score": "CLE 77 - 78 GSW", "desc": "LeBron forces his way to the paint and gets a layup.", "isHighlight": False},
        {"clock": "9:35",  "quarter": "Q4", "score": "CLE 77 - 81 GSW", "desc": "Curry hits a deep catch-and-shoot THREE! Warriors push the lead to 4.", "isHighlight": True},
        {"clock": "8:55",  "quarter": "Q4", "score": "CLE 77 - 81 GSW", "desc": "Kyrie gets to the line but misses both. Cleveland still down.", "isHighlight": False},
        {"clock": "8:20",  "quarter": "Q4", "score": "CLE 80 - 81 GSW", "desc": "Kyrie Irving answers with a quick crossover three of his own!", "isHighlight": True},
        {"clock": "7:55",  "quarter": "Q4", "score": "CLE 82 - 81 GSW", "desc": "Curry turns it over! LeBron on the fast break... THUNDEROUS DUNK!", "isHighlight": True},
        {"clock": "7:20",  "quarter": "Q4", "score": "CLE 82 - 84 GSW", "desc": "Klay Thompson answers with a quick three from the left wing.", "isHighlight": False},
        {"clock": "6:40",  "quarter": "Q4", "score": "CLE 84 - 84 GSW", "desc": "LeBron drives, dishes to Love who calmly hits the open three!", "isHighlight": False},
        {"clock": "6:10",  "quarter": "Q4", "score": "CLE 84 - 84 GSW", "desc": "Klay Thompson hits a tough fadeaway to keep up with Cleveland.", "isHighlight": False},
        {"clock": "5:24",  "quarter": "Q4", "score": "CLE 84 - 86 GSW", "desc": "Draymond Green draws a foul on Love and hits both free throws. Warriors back in front.", "isHighlight": False},
        {"clock": "4:39",  "quarter": "Q4", "score": "CLE 87 - 86 GSW", "desc": "LeBron draws a foul on Iguodala — hits the shot AND the free throw! AND-ONE!", "isHighlight": True},
        {"clock": "4:15",  "quarter": "Q4", "score": "CLE 87 - 89 GSW", "desc": "Klay Thompson ties it up again with a clutch layup! Back-and-forth battle.", "isHighlight": False},
        {"clock": "3:45",  "quarter": "Q4", "score": "CLE 89 - 89 GSW", "desc": "Kyrie hits two free throws to reclaim the lead!", "isHighlight": False},
        {"clock": "3:10",  "quarter": "Q4", "score": "CLE 89 - 89 GSW", "desc": "Durant pump fakes, drives and hits a fadeaway over LeBron. Tied again!", "isHighlight": True},
        {"clock": "2:35",  "quarter": "Q4", "score": "CLE 89 - 89 GSW", "desc": "Timeout Golden State. Both teams are exhausted. This is basketball at its purest.", "isHighlight": False},
        {"clock": "1:50",  "quarter": "Q4", "score": "CLE 89 - 89 GSW", "desc": "IGUODALA ON THE FAST BREAK— LEBRON JAMES COMES FROM BEHIND!!! THE CHASE DOWN BLOCK!!!!", "isHighlight": True},
        {"clock": "0:53",  "quarter": "Q4", "score": "CLE 92 - 89 GSW", "desc": "KYRIE IRVING! Step-back three over Curry with :53 left!!! THE SHOT!!!!", "isHighlight": True},
        {"clock": "0:30",  "quarter": "Q4", "score": "CLE 92 - 89 GSW", "desc": "Curry isolated on Kevin Love, forced into a desperate 3-pointer... MISSES!", "isHighlight": True},
        {"clock": "0:10",  "quarter": "Q4", "score": "CLE 93 - 89 GSW", "desc": "LeBron fouled hard by Green going for the dunk. Sinks one of two.", "isHighlight": False},
        {"clock": "0:00",  "quarter": "Q4", "score": "CLE 93 - 89 GSW", "desc": "GAME OVER! CLEVELAND CAVALIERS WIN THE 2016 NBA CHAMPIONSHIP! The 3-1 comeback is complete!", "isHighlight": True},
    ],

    # ─────────────────────────────────────────────
    # 2023 PLAYOFFS GAME 6 — LAL vs GSW — FULL GAME
    # ─────────────────────────────────────────────
    "2023_playoffs_lal_gsw": [
        # ── Q1 ──
        {"clock": "12:00", "quarter": "Q1", "score": "LAL 0 - 0 GSW",  "desc": "Tip-off! Klutch moment in San Francisco — both teams know what's at stake.", "isHighlight": False},
        {"clock": "11:35", "quarter": "Q1", "score": "LAL 2 - 0 GSW",  "desc": "LeBron James straight-line drive to the bucket. Easy two.", "isHighlight": False},
        {"clock": "11:08", "quarter": "Q1", "score": "LAL 2 - 3 GSW",  "desc": "Curry hits a pull-up three over James on the first possession!", "isHighlight": True},
        {"clock": "10:40", "quarter": "Q1", "score": "LAL 4 - 3 GSW",  "desc": "Anthony Davis catches on the low-block and spins baseline for two.", "isHighlight": False},
        {"clock": "10:05", "quarter": "Q1", "score": "LAL 4 - 6 GSW",  "desc": "Klay Thompson catches in the corner, no hesitation — three pointer!", "isHighlight": True},
        {"clock": "9:30",  "quarter": "Q1", "score": "LAL 7 - 6 GSW",  "desc": "LeBron hits from mid-range after a pump-fake draws a foul. Plus the free throw!", "isHighlight": False},
        {"clock": "8:55",  "quarter": "Q1", "score": "LAL 7 - 9 GSW",  "desc": "Jordan Poole goes around the screen and hits a step-back two.", "isHighlight": False},
        {"clock": "8:20",  "quarter": "Q1", "score": "LAL 10 - 9 GSW", "desc": "Davis catches a lob from LeBron and throws it DOWN!", "isHighlight": True},
        {"clock": "7:45",  "quarter": "Q1", "score": "LAL 10 - 12 GSW","desc": "Curry orchestrates a beautiful pick-and-roll with Draymond, hits the floater.", "isHighlight": False},
        {"clock": "7:10",  "quarter": "Q1", "score": "LAL 13 - 12 GSW","desc": "Austin Reaves hits a big corner three to take the lead back!", "isHighlight": True},
        {"clock": "6:35",  "quarter": "Q1", "score": "LAL 13 - 15 GSW","desc": "Wiggins goes hard baseline and hits the reverse layup.", "isHighlight": False},
        {"clock": "5:55",  "quarter": "Q1", "score": "LAL 16 - 15 GSW","desc": "LeBron posts up Draymond and hits the running hook shot.", "isHighlight": False},
        {"clock": "5:15",  "quarter": "Q1", "score": "LAL 16 - 18 GSW","desc": "Poole goes for three and hits it off a Curry screen!", "isHighlight": False},
        {"clock": "4:40",  "quarter": "Q1", "score": "LAL 18 - 18 GSW","desc": "Rui Hachimura comes off the bench and immediately drains a mid-range jumper.", "isHighlight": False},
        {"clock": "4:02",  "quarter": "Q1", "score": "LAL 18 - 21 GSW","desc": "Curry steps back from 35 feet and hits it. The crowd erupts!", "isHighlight": True},
        {"clock": "3:25",  "quarter": "Q1", "score": "LAL 21 - 21 GSW","desc": "Anthony Davis draws two fouls on the block and hits all three free throws.", "isHighlight": False},
        {"clock": "2:50",  "quarter": "Q1", "score": "LAL 21 - 24 GSW","desc": "Green draws a foul on James in the post and hits both shots.", "isHighlight": False},
        {"clock": "2:10",  "quarter": "Q1", "score": "LAL 23 - 24 GSW","desc": "LeBron James drives past Wiggins and gets a soft layup to go.", "isHighlight": False},
        {"clock": "1:30",  "quarter": "Q1", "score": "LAL 25 - 24 GSW","desc": "Reaves picks off a Curry pass and sprints the other way for the layup!", "isHighlight": True},
        {"clock": "0:45",  "quarter": "Q1", "score": "LAL 25 - 27 GSW","desc": "Klay Thompson hits a running floater before the buzzer. Warriors lead 27-25.", "isHighlight": False},
        # ── Q2 ──
        {"clock": "12:00", "quarter": "Q2", "score": "LAL 25 - 27 GSW","desc": "Second quarter begins. Warriors hold a narrow 2-point cushion.", "isHighlight": False},
        {"clock": "11:20", "quarter": "Q2", "score": "LAL 28 - 27 GSW","desc": "Jarred Vanderbilt off the bench with back-to-back put-backs. Lakers take the lead!", "isHighlight": True},
        {"clock": "10:45", "quarter": "Q2", "score": "LAL 28 - 30 GSW","desc": "Poole catches the pass in transition and hits an off-balance three.", "isHighlight": False},
        {"clock": "10:10", "quarter": "Q2", "score": "LAL 31 - 30 GSW","desc": "Davis knocks down a 15-foot fadeaway after an Anthony Edwards iso.", "isHighlight": False},
        {"clock": "9:30",  "quarter": "Q2", "score": "LAL 31 - 33 GSW","desc": "Curry comes off a screen and drains a pull-up three over the outstretched hand.", "isHighlight": True},
        {"clock": "8:52",  "quarter": "Q2", "score": "LAL 34 - 33 GSW","desc": "LeBron draws a foul on the drive and sinks both free throws.", "isHighlight": False},
        {"clock": "8:15",  "quarter": "Q2", "score": "LAL 34 - 36 GSW","desc": "Green with a beautiful full-court skip pass to a cutting Wiggins, easy layup.", "isHighlight": False},
        {"clock": "7:38",  "quarter": "Q2", "score": "LAL 37 - 36 GSW","desc": "LeBron demands the ball, backs down, and hits the post hook!", "isHighlight": False},
        {"clock": "7:00",  "quarter": "Q2", "score": "LAL 37 - 39 GSW","desc": "Klay hits two in a row from the same spot on the right wing.", "isHighlight": True},
        {"clock": "6:20",  "quarter": "Q2", "score": "LAL 40 - 39 GSW","desc": "Reaves with a floater in the lane over the big man!", "isHighlight": False},
        {"clock": "5:42",  "quarter": "Q2", "score": "LAL 40 - 42 GSW","desc": "Curry goes behind the back, pulls up, and hits the three. Smooth!", "isHighlight": True},
        {"clock": "5:05",  "quarter": "Q2", "score": "LAL 43 - 42 GSW","desc": "Davis hits a turn-around hook over Looney. Three point lead again!", "isHighlight": False},
        {"clock": "4:25",  "quarter": "Q2", "score": "LAL 43 - 45 GSW","desc": "Draymond Green with a rare offensive contribution — drives and finishes.", "isHighlight": False},
        {"clock": "3:48",  "quarter": "Q2", "score": "LAL 46 - 45 GSW","desc": "Hachimura knocks down a long two off a LeBron drive-and-kick. Lakers back on top!", "isHighlight": False},
        {"clock": "3:10",  "quarter": "Q2", "score": "LAL 46 - 48 GSW","desc": "Poole draws a foul on Reaves and sinks both free throws before the break.", "isHighlight": False},
        {"clock": "2:28",  "quarter": "Q2", "score": "LAL 49 - 48 GSW","desc": "LeBron James hits a massive three to put Lakers up going into halftime!", "isHighlight": True},
        {"clock": "1:40",  "quarter": "Q2", "score": "LAL 49 - 51 GSW","desc": "Thompson and the Warriors respond immediately with a drive from Klay.", "isHighlight": False},
        {"clock": "0:50",  "quarter": "Q2", "score": "LAL 51 - 51 GSW","desc": "LeBron to Davis on the lob! Alley-oop brings it back to a tie.", "isHighlight": True},
        {"clock": "0:12",  "quarter": "Q2", "score": "LAL 51 - 51 GSW","desc": "Curry heaves from half-court. NO GOOD. Halftime. It's all tied up at 51.", "isHighlight": False},
        # ── Q3 ──
        {"clock": "12:00", "quarter": "Q3", "score": "LAL 51 - 51 GSW","desc": "Third quarter underway. Both crowds on their feet.", "isHighlight": False},
        {"clock": "11:30", "quarter": "Q3", "score": "LAL 53 - 51 GSW","desc": "LeBron James immediately hits a floater off the jump ball. Lakers strike first!", "isHighlight": False},
        {"clock": "10:55", "quarter": "Q3", "score": "LAL 53 - 54 GSW","desc": "Curry answers with a pull-up off the dribble. Warriors retake the lead.", "isHighlight": False},
        {"clock": "10:20", "quarter": "Q3", "score": "LAL 56 - 54 GSW","desc": "Anthony Davis blocks Poole and Davis converts the other end!", "isHighlight": True},
        {"clock": "9:45",  "quarter": "Q3", "score": "LAL 56 - 57 GSW","desc": "Wiggins drives through Davis and converts a tough one.", "isHighlight": False},
        {"clock": "9:08",  "quarter": "Q3", "score": "LAL 58 - 57 GSW","desc": "LeBron draws the foul on the drive and goes 2-for-2 at the line.", "isHighlight": False},
        {"clock": "8:30",  "quarter": "Q3", "score": "LAL 58 - 60 GSW","desc": "Curry in isolation — one dribble, steps back — BANG! Three!", "isHighlight": True},
        {"clock": "7:50",  "quarter": "Q3", "score": "LAL 61 - 60 GSW","desc": "Reaves drives past Curry and lays it in softly!", "isHighlight": False},
        {"clock": "7:12",  "quarter": "Q3", "score": "LAL 61 - 63 GSW","desc": "Thompson catches in his sweet spot — mid-range — hits it!", "isHighlight": False},
        {"clock": "6:35",  "quarter": "Q3", "score": "LAL 64 - 63 GSW","desc": "Davis catches a lob from LeBron and completes the and-one!", "isHighlight": True},
        {"clock": "5:58",  "quarter": "Q3", "score": "LAL 64 - 66 GSW","desc": "Curry goes around three screens and buries a three. Crowd goes CRAZY at Chase Center.", "isHighlight": True},
        {"clock": "5:20",  "quarter": "Q3", "score": "LAL 67 - 66 GSW","desc": "LeBron puts back a miss with a one-handed slam!", "isHighlight": True},
        {"clock": "4:42",  "quarter": "Q3", "score": "LAL 67 - 69 GSW","desc": "Poole hits a mid-range off a Curry drive-and-kick. Warriors retake the lead.", "isHighlight": False},
        {"clock": "4:05",  "quarter": "Q3", "score": "LAL 70 - 69 GSW","desc": "Vanderbilt steals a Draymond pass and Reaves lays it in!", "isHighlight": True},
        {"clock": "3:28",  "quarter": "Q3", "score": "LAL 70 - 72 GSW","desc": "Klay Thompson hits from the right wing again! He's been so consistent.", "isHighlight": False},
        {"clock": "2:48",  "quarter": "Q3", "score": "LAL 73 - 72 GSW","desc": "LeBron muscles through contact on the drive and finishes with the foul!", "isHighlight": True},
        {"clock": "2:08",  "quarter": "Q3", "score": "LAL 73 - 75 GSW","desc": "Draymond feeds Curry on the roll, Curry banks it in off glass.", "isHighlight": False},
        {"clock": "1:28",  "quarter": "Q3", "score": "LAL 76 - 75 GSW","desc": "Anthony Davis with a monster three-pointer! He can do it all!", "isHighlight": True},
        {"clock": "0:48",  "quarter": "Q3", "score": "LAL 76 - 77 GSW","desc": "Wiggins makes two free throws to give Warriors the lead going into Q4.", "isHighlight": False},
        {"clock": "0:10",  "quarter": "Q3", "score": "LAL 78 - 77 GSW","desc": "Reaves hits a buzzer-beating mid-range! LAKERS LEAD HEADING INTO Q4!", "isHighlight": True},
        # ── Q4 ──
        {"clock": "12:00", "quarter": "Q4", "score": "LAL 78 - 77 GSW","desc": "FINAL QUARTER. Lakers lead by 1. This is do-or-die for Golden State.", "isHighlight": False},
        {"clock": "11:20", "quarter": "Q4", "score": "LAL 81 - 77 GSW","desc": "Davis wins a battle on the block and scores, plus the foul!", "isHighlight": True},
        {"clock": "10:42", "quarter": "Q4", "score": "LAL 81 - 80 GSW","desc": "Curry hits two free throws after getting bumped by LeBron on the drive.", "isHighlight": False},
        {"clock": "10:05", "quarter": "Q4", "score": "LAL 83 - 80 GSW","desc": "LeBron James with a back-down, turns baseline, hits the hook shot!", "isHighlight": False},
        {"clock": "9:28",  "quarter": "Q4", "score": "LAL 83 - 83 GSW","desc": "Klay Thompson hits back-to-back threes in 21 seconds! THE WARRIORS ARE ALIVE!", "isHighlight": True},
        {"clock": "8:50",  "quarter": "Q4", "score": "LAL 86 - 83 GSW","desc": "LeBron isolation on Draymond — drives left, reverse layup! And one!", "isHighlight": True},
        {"clock": "8:12",  "quarter": "Q4", "score": "LAL 86 - 86 GSW","desc": "Curry answers with a 28-foot three from the logo. This man is UNSTOPPABLE.", "isHighlight": True},
        {"clock": "7:35",  "quarter": "Q4", "score": "LAL 89 - 86 GSW","desc": "Reaves hits a corner three off a LeBron hand-off! Lakers push it back to three!", "isHighlight": True},
        {"clock": "6:58",  "quarter": "Q4", "score": "LAL 89 - 89 GSW","desc": "Poole drives the lane, gets contact, converts the layup and the free throw!", "isHighlight": False},
        {"clock": "6:20",  "quarter": "Q4", "score": "LAL 92 - 89 GSW","desc": "Anthony Davis massive block on Poole, then Davis converts the other end!", "isHighlight": True},
        {"clock": "5:40",  "quarter": "Q4", "score": "LAL 92 - 92 GSW","desc": "Klay Thompson ties it with a catch-and-fire three. Ice cold!", "isHighlight": True},
        {"clock": "5:03",  "quarter": "Q4", "score": "LAL 95 - 92 GSW","desc": "LeBron James drives and finishes through contact with a thunderous two-handed flush!", "isHighlight": True},
        {"clock": "4:28",  "quarter": "Q4", "score": "LAL 95 - 95 GSW","desc": "Curry buries a 31-footer to tie the game again! Oracle Center loses its mind!", "isHighlight": True},
        {"clock": "3:52",  "quarter": "Q4", "score": "LAL 98 - 95 GSW","desc": "Reaves gets fouled on a drive, goes 1-of-2. Davis gets the offensive rebound and tip-in!", "isHighlight": True},
        {"clock": "3:15",  "quarter": "Q4", "score": "LAL 98 - 97 GSW","desc": "Thompson hits yet another huge three-pointer to make it a one-point game!", "isHighlight": True},
        {"clock": "2:38",  "quarter": "Q4", "score": "LAL 100 - 97 GSW","desc": "LeBron backs down Draymond and hits a turnaround jumper. Lakers up three!", "isHighlight": False},
        {"clock": "2:02",  "quarter": "Q4", "score": "LAL 100 - 100 GSW","desc": "CURRY ANSWERS FROM DEEP AGAIN! This game is absolutely insane!", "isHighlight": True},
        {"clock": "1:28",  "quarter": "Q4", "score": "LAL 103 - 100 GSW","desc": "Anthony Davis gets isolated on Looney — spins and hits the baby hook!", "isHighlight": False},
        {"clock": "0:55",  "quarter": "Q4", "score": "LAL 103 - 102 GSW","desc": "Wiggins floater splits two defenders. One point game with under a minute!", "isHighlight": True},
        {"clock": "0:28",  "quarter": "Q4", "score": "LAL 106 - 102 GSW","desc": "LeBron James draws two more free throws and hits BOTH! Lakers now up four!", "isHighlight": True},
        {"clock": "0:10",  "quarter": "Q4", "score": "LAL 106 - 104 GSW","desc": "Curry hits a quick two to make it a two possession game! Desperate times!", "isHighlight": False},
        {"clock": "0:03",  "quarter": "Q4", "score": "LAL 107 - 104 GSW","desc": "LeBron fouled intentionally. Hits one of two. Lakers up three!", "isHighlight": False},
        {"clock": "0:00",  "quarter": "Q4", "score": "LAL 107 - 104 GSW","desc": "FINAL BUZZER! Los Angeles Lakers eliminate Golden State Warriors! LeBron's mission is DONE!", "isHighlight": True},
    ]
}
